# =====================================================
# Render.com Deployment Configuration
# =====================================================
# This file configures automatic deployment of the
# Task Manager backend on Render's free tier.
# =====================================================

services:
  - type: web
    name: task-manager-backend
    runtime: java
    plan: free

    # Build Configuration
    buildCommand: mvn clean package -DskipTests
    startCommand: java -Dserver.port=$PORT -jar target/task-manager-backend-1.0.0.jar

    # Health Check Configuration
    healthCheckPath: /actuator/health

    # Environment Variables
    # Configure these in Render Dashboard: Settings > Environment
    envVars:
      # Database Configuration (from Supabase)
      - key: DATABASE_URL
        sync: false  # Set manually in Render dashboard

      - key: FLYWAY_URL
        sync: false  # Set manually in Render dashboard

      - key: DATABASE_USERNAME
        sync: false  # Set manually in Render dashboard

      - key: DATABASE_PASSWORD
        sync: false  # Set manually in Render dashboard

      # JWT Configuration
      - key: JWT_SECRET
        generateValue: true  # Render will auto-generate a secure secret

      - key: JWT_EXPIRATION_MS
        value: 86400000  # 24 hours

      # Spring Configuration
      - key: SPRING_PROFILES_ACTIVE
        value: prod

      - key: PORT
        value: 8080

      # CORS Configuration (update after deploying frontend)
      # - key: CORS_ALLOWED_ORIGINS
      #   value: https://your-app.vercel.app,http://localhost:5173

# =====================================================
# Deployment Instructions
# =====================================================
#
# 1. Push this file to your GitHub repository
#
# 2. In Render Dashboard:
#    - New > Web Service
#    - Connect your GitHub repository
#    - Render will auto-detect this file
#
# 3. Add Environment Variables:
#    Copy from your local .env file:
#    - DATABASE_URL
#    - FLYWAY_URL
#    - DATABASE_USERNAME
#    - DATABASE_PASSWORD
#
# 4. Deploy!
#    - First deployment takes ~5-7 minutes
#    - Subsequent deploys are faster
#    - Free tier sleeps after 15 min inactivity
#    - Wakes automatically on first request (~30 sec)
#
# 5. Get your backend URL:
#    https://task-manager-backend.onrender.com
#
# 6. Update CORS in SecurityConfig.java:
#    Add your Vercel frontend URL to allowed origins
#
# =====================================================
